In [85]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [23]:
arr1[2]

3

In [3]:
arr1[2]=5

In [4]:
arr1

array([1, 2, 5])

In [11]:
arr2 =np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
print("the shape is 2 row and 3 columns:",arr2.shape)

the shape is 2 row and 3 columns: (2, 3)


In [10]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [14]:
arr3=np.array(['India','china','usa','mexico'])
print(arr3)

['India' 'china' 'usa' 'mexico']


In [16]:
arr3[3]

'mexico'

In [27]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [40]:
arr=np.linspace(0,2,20)
print(arr)

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]


In [41]:
arr=np.random.rand(10)
print(arr)
print('\n')
arr= np.random.rand(3,4)
print(arr)

[0.13500644 0.85152867 0.1330243  0.44122674 0.3262685  0.63490884
 0.0687695  0.66217505 0.1183444  0.43907164]


[[0.67040182 0.13964011 0.97078298 0.54432332]
 [0.47004027 0.41385433 0.36173126 0.11981005]
 [0.21727102 0.70453876 0.01799847 0.00534796]]


In [46]:
print(np.full((5,4),1.1))

[[1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1]
 [1.1 1.1 1.1 1.1]]


In [49]:
arr=[0,1,2]
print(np.repeat(arr,4))

[0 0 0 0 1 1 1 1 2 2 2 2]


In [52]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [53]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [56]:
arr=np.random.rand(5,5)
print(arr)

[[0.8817744  0.07327285 0.53095901 0.39762508 0.65922738]
 [0.73417368 0.3233446  0.8521809  0.86738828 0.64576616]
 [0.04608411 0.52393489 0.28619072 0.63982743 0.33331997]
 [0.14677823 0.772257   0.66817242 0.97607172 0.91951648]
 [0.7082677  0.77271454 0.08345971 0.88573906 0.3304318 ]]


In [59]:
print(np.sum(arr,axis=0))

[2.51707811 2.46552389 2.42096275 3.76665156 2.88826178]


In [62]:
print(np.sum(arr,axis=1))

[2.54285871 3.42285361 1.82935711 3.48279585 2.7806128 ]


In [63]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


0.5623391235048326
0.6457661586124575
0.285100468632887
0.0812822772146918


In [66]:
arr=np.random.rand(5,5)
print(arr)

[[0.06554404 0.08871633 0.24384491 0.92317746 0.67337723]
 [0.71029743 0.07600227 0.68504708 0.57920323 0.79772771]
 [0.91432125 0.3117001  0.62793431 0.41836198 0.96918555]
 [0.41264443 0.44431116 0.499346   0.55111995 0.82327465]
 [0.59767522 0.86001279 0.39476193 0.20726594 0.72941023]]


In [67]:
print(np.sort(arr,axis=1))

[[0.06554404 0.08871633 0.24384491 0.67337723 0.92317746]
 [0.07600227 0.57920323 0.68504708 0.71029743 0.79772771]
 [0.3117001  0.41836198 0.62793431 0.91432125 0.96918555]
 [0.41264443 0.44431116 0.499346   0.55111995 0.82327465]
 [0.20726594 0.39476193 0.59767522 0.72941023 0.86001279]]


In [68]:
arr=np.array([4,5,6,7])

In [73]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [75]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [78]:
arr2=np.array([4,5,6,7,8,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  7  8  9 10 11]


[ 4  6  7  9 10 11]


In [79]:
arr1=np.array([[1,2,3,4,],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [80]:
cat=np.concatenate((arr1,arr2),axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [83]:
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
